## Write a Numpy program to compute the multiplication of two given matrixes

In [2]:
import numpy as np
m1=[[1,2],[3,4]]
m2=[[2,4],[5,6]]
print(m1)
print(m2)

[[1, 2], [3, 4]]
[[2, 4], [5, 6]]


In [5]:
result=np.dot(m1,m2)
result

array([[12, 16],
       [26, 36]])

## Write a NumPy program to compute the determinant of a given square array

In [9]:
from numpy import linalg as LA
m3=np.array([[1,1],[2,2]])
m3

array([[1, 1],
       [2, 2]])

In [10]:
result=np.linalg.det(m3)
result

0.0

## Write a NumPy program to compute the cross product of two given vectors

In [11]:
import numpy as np
m1=[[0,1],[2,3]]
m2=[[4,6],[3,5]]

[[4, 6], [3, 5]]

In [12]:
result1=np.cross(m1,m2)
result2=np.cross(m2,m1)
print(result1)
print(result2)

[-4  1]
[ 4 -1]


## Write a NumPy program to compute the condition number of a given matrix
the condition number of a function measures how much the output value of the function can change for a small change in the input argument. This is used to measure how sensitive a function is to changes or errors in the input, and how much error in the output results from an error in the input.

*hint: look for something similar in the `linalg` module*

In [15]:
from numpy import linalg as LA
m1=np.array([[1,1],[2,2]])
m1

array([[1, 1],
       [2, 2]])

In [16]:
res=np.linalg.cond(m1)
res

2.0140709820486308e+16

## Write a NumPy program to compute the inverse of a given matrix

In [19]:
from numpy.linalg import inv
m1=np.array([[1,2],[3,4]])
m1

array([[1, 2],
       [3, 4]])

In [21]:
res=np.linalg.inv(m1)
res

array([[-2. ,  1. ],
       [ 1.5, -0.5]])